Vagrant.configure("2") do |config|
    config.vm.box = "StefanScherer/windows_2019"
    config.vm.guest = :windows
    config.vm.communicator = "winrm"
    config.vm.boot_timeout = 600
    config.vm.graceful_halt_timeout = 600
  
    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine.
    config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "msrdp", auto_correct: true
    config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
  
    config.vm.provision "shell", path:"./ConfigureRemotingForAnsible.ps1"
  end