---
# default file for arillso.ntp

# List of NTP servers for time synchronization.
# Special case if an inventory group NAS is
# present it will be taken as the first NTP server.
ntp_server:
  - "{{ groups['NAS'] | default('0.pool.ntp.org') }}"
  - '1.pool.ntp.org'
  - '2.pool.ntp.org'
  - '3.pool.ntp.org'

# Linux

# Restrictions are used to control access to your ntpd.
ntp_config_restrict:
  - '-4 default kod notrap nomodify nopeer noquery'
  - '-6 default kod notrap nomodify nopeer noquery'
  - '127.0.0.1'
  - '::1'

# Specifies to which interface ntp should be appended.
ntp_config_listen: []

# Next ntp Configurrations details.
ntp_config_filegen:
  - 'loopstats file loopstats type day enable'
  - 'peerstats file peerstats type day enable'
  - 'clockstats file clockstats type day enable'
ntp_config_statistics: 'loopstats peerstats clockstats'
ntp_config_crypto: ''
ntp_config_includefile: ''
ntp_config_keys: ''
ntp_config_trustedkey: ''
ntp_config_requestkey: ''
ntp_config_controlkey: ''
ntp_config_broadcast: ''
ntp_config_broadcastclient: ''
ntp_config_multicastclient: ''
ntp_config_tinker_panic_enabled: ''

# Windows

# Specifies whether the time server is configured via
# Windows GPO so that it is not permanently overwritten.
ntp_GPO_enable: '{{ default_GPO_enable | default(false) }}'

# Possible settings are described under the following link:
# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsTimeService::W32TIME_POLICY_CONFIGURE_NTPCLIENT
ntp_time_type: 'NTP'
ntp_crosssitesyncflags: '2'
ntp_resolvepeerbackoffminutes: '15'
ntp_resolvepeerbackoffmaxtimes: '7'
ntp_specialpollinterval: '1024'
ntp_eventlogflags: '0'

# Possible NTP flags that can be used under windows.
# 0x01    SpecialInterval
# 0x02    UseAsFallbackOnly
# 0x04    SymmatricActive
# 0x08    Client
ntp_flag: '0x01'
