---
# tasks file for arillso.ntp

- name: 'linux : install ntp'
  become: true
  package:
    name: '{{ ntp_package_name }}'
  notify: enabled ntp
  tags:
    - packages

- name: 'linux : copy config'
  become: true
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - enabled ntp
    - restart ntp
  tags:
    - configuration
