---
# tasks file for arillso.ntp

- name: 'windows : Sets NTP as time protocol'
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\W32time\Parameters
    name: Type
    data: '{{ ntp_time_type }}'
    type: string
  when: not ntp_GPO_enable
  notify:
    - update ntp config
  tags:
    - configuration

- name: 'windows : Sets NTP Server'
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\W32time\Parameters
    name: NtpServer
    data: "{{ ntp_server | join(',' + ntp_flag + ' ') }}"
    type: string
  when: not ntp_GPO_enable
  notify:
    - update ntp config
  tags:
    - configuration

- name: 'windows : Sets NTP Client Settings'
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\W32time\TimeProviders\NtpClient
    name: '{{ item.name }}'
    data: '{{ item.data }}'
    type: dword
  when: not ntp_GPO_enable
  with_items:
    - name: CrossSiteSyncFlags
      data: '{{ ntp_crosssitesyncflags }}'
    - name: ResolvePeerBackoffMinutes
      data: '{{ ntp_resolvepeerbackoffminutes }}'
    - name: ResolvePeerBackoffMaxTimes
      data: '{{ ntp_resolvepeerbackoffmaxtimes }}'
    - name: SpecialPollInterval
      data: '{{ ntp_specialpollinterval }}'
    - name: EventLogFlags
      data: '{{ ntp_eventlogflags }}'
  notify:
    - update ntp config
  tags:
    - configuration
