- name: Deploy Tomcat on server
  hosts: tomcat
  become: yes
  become_method: sudo
  roles:
  - common
  - tomcat
  vars:
    deploy_env: testing
    is_tomcat: true
    app_type: tomcat
    tomcat_ver: 9.0.30                          # Tomcat version to install
    ui_manager_user: manager                    # User who can access the UI manager section only
    ui_manager_pass: Str0ngManagerP@ssw3rd      # UI manager user password
    ui_admin_username: admin                    # User who can access bpth manager and admin UI sections
    ui_admin_pass: Str0ngAdminP@ssw3rd          # UI admin password